# =============================================
# CONFIGURAÇÃO GERAL - E-COMMERCE 2026
# =============================================

# URL do e-commerce (mude conforme o site que você vai testar)
url.base=https://www.saucedemo.com
browser=chrome
timeout.explicit=15